### ISSUE TITLE
restart queue redis (appendonly yes) would enqueued some processed tasks again

### ISSUE THREAD

**Issue by dawncold** [closeio/tasktiger#78]
~~I found some tasks which are done successfully are enqueued again.~~

~~I have a transactional sms queue, send sms via another platform like Twilio, I found one sms task is done successfully (found sms record on sms platform), and there is no failed tasks in queue.~~

~~Every night we will backup database and redis aof files, during backup, we will shutdown database and redis, but we don't shutdown tasktiger worker processes, so it will raise exception of redis connection and it will be restarted by `supervisord`, after restart tasktiger several times, some sms tasks are enqueued again even they have been processed successfully.~~

~~I have tested, if I only restart my redis-server, some non-existing tasks will be enqueued as if my redis is rollback.~~

***
Today, we think we have found root cause of this issue.

`Tasktiger` use some `lua` scripts for utilizing `lua` language features, such as `for`, `function`. The customized `pipeline` script calls other `lua` scripts, that will be recorded in `AOF` file like this: 

> execute pipeline script with some sub-scripts: script A SHA1 and args for A, script B SHA1 and args for B, ...

`BGWRITEAOF` will remove `SCRIPT LOAD`, but you can still call these scripts via `EVALSHA` before restart `redis` or `SCRIPT FLUSH`.

When `redis` loading data from `AOF` file, `pipeline` script using `EVALSHA` will be failed because scripts are not loaded, so some tasks are not removed from active queue, `worker` will move them to `queued` and process them again.

We have to `BGREWRITEAOF` every hour and rewrite `AOF` before shutdown `redis`.

**Comment by thomasst** [comment]
Thanks for reporting this! Do we need to call `SCRIPT LOAD` *within* the pipeline Lua script? I haven't tried if this works, but my guess is it would solve the problem.

**Comment by dawncold** [comment]
I think it should be fix if `SCRIPT LOAD` is called before Lua script, and I don't know why Redis don't do this.

**Comment by thomasst** [comment]
We directly call scripts by the SHA sum from the `_G` variable so I don't think Redis would know that it needs to load additional scripts before executing our Lua script.
https://github.com/closeio/tasktiger/blob/master/tasktiger/lua/execute_pipeline.lua#L46

Maybe the solution could be to use a pipeline that first loads all the scripts (regardless of whether they're already loaded), and then runs the actual pipeline Lua script. That way Redis shouldn't break it up.

**Comment by duxiaoyao** [comment]
I am afraid that you guys misunderstand the problem. Let me try to clarify it.

Shutdown redis, commands loading scripts appear before commands callinging scripts in AOF file. Start redis, replay commands in AOF, scripts are loaded first, then call, and everything is okay.

Now make a BGWRITEAOF, AOF is rewritten, commands loading scripts are not in AOF any more. As tasks are processed, commands calling scripts are appended to AOF, but no commands loading scripts appended before because we redis has those scripts in script cache. When restarting redis, script cache is empty, replay AOF, commands calling scripts could not run as those scripts are not found in script cache.

The state of a running redis instance includes two parts: data and script cache. Without BGWRITEAOF, AOF is consistent with redis state both data and script cache, commands loading scripts in AOF ensure the consistency with script cache of the current running redis instance. After BGWRITEAOF, AOF is consistent with redis data state but lose redis script cache state. Since, loading scripts will not append loading-scripts commands to AOF as redis has those scripts already in script cache, calling scripts will append calling-scripts commands to AOF. Upon redis restart, the script cache is not persisted and started as empty, those calling-scripts commands after BGWRITEAOF in AOF could not run and would not change data as they are supposed to do, and now then, the redis data state is not consistent with one before shutdown. In terms of tasktiger, tasks processed after BGWRITEAOF but before redis shutdown are now regarded as not processed.

This seems a problem about redis. BGWRITEAOF should append commands loading scripts in script cache to AOF, or clear script cache right before forking the process for BGWRITEAOF.
